apiVersion: apps/v1
kind: Deployment
metadata:
  name: web2-pod-deployment
  namespace: default
  labels:
    name: web2-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: web2
  template:
    metadata:
      labels:
        name: web2
    spec:
      containers:  
        - name: node
          image: gcr.io/rosy-cache-200605/nginx-pvr1
          imagePullPolicy: IfNotPresent 
          ports:
            - containerPort: 80
