apiVersion: v1 
kind: Service
metadata:
  name: web2-service
  namespace: default
spec:
  selector:
    name: web2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer 
